#!/bin/bash
CMAP_PATH="$HOME/.local/share/root-cmap"

case "$1" in
  "-s")
    echo "$CMAP_PATH/scripts"
    ;;
  "-j")
    echo "$CMAP_PATH/json"
    ;;
  "-py")
    echo "$CMAP_PATH/rcm_py"
    ;;
  "-l")
    echo "$CMAP_PATH/rcm_lua"
    ;;
  "-pyi")
    echo "$CMAP_PATH/rcm_py/bin/activate"
    ;;
  *)
    env -C "$CMAP_PATH" ./root_ctrl_mapper "$@"
    ;;
esac
